### ISSUE TITLE
Answering Questions

### ISSUE THREAD

**Issue by yala** [yala/learning_interactive_planning#2]
# Question Asking System
## We want to support:
1. Answer Quality Baselines 
   - [x] One-Match: 1 matched sentence
   - [x] K-Match: at-most-k matched sentences 
   - [x] BagOfWords: all matched sentences (now called KBagOfWords)
   - [x] k-Random: random k sentences from wiki
   - [ ] Gold: return gold relation to be extracted from text (option for all of the above)
   - [ ] k-WSJ: random k sentences from WSJ or other unrelated corpora 
2. Question Templates
   - [x] Rule 0: A, actions (e.g. `(0, "this-is-an-action")`)
   - [x] Rule 1: T, single thing (e.g. `(1, "wood")`)
   - [x] Rule 2: PxT, single subgoal (e.g. `(2, "have pickaxe")`)
   - [x] Rule 3: pair of subgoals (e.g. `(3, "have pickaxe burn wood")`)
## Left to do
- [x] Building RPC so that @yala can call
- [x] Document coding convention
## Calling convention

`(template_number, "word1 word2")`
## Return Convention

```
sentence in clear
Features

---
sentence in clear
Features
```

For more detailed protocol mechanics, see [RPC](https://github.com/flare-ai/learning_from_questions/pull/8)
## Known issues

Converting keywords to words (done by the IR system)

**Comment by yala** [comment]
@sebboyer @nicola,
Let's discuss a calling / return convention here

Feel free to add more baselones

**Comment by nicola** [comment]
@yala the 1-matched sentence, how do I choose which sentence is the right sentence?

**Comment by yala** [comment]
Randomly from the set

**Comment by nicola** [comment]
I updated calling convention and return function

**Comment by nicola** [comment]
@yala what is the difference between single object and single thing?

**Comment by nicola** [comment]
@yala comparing two subgoals means `wood pickaxe` or `have wood make pickaxe` ?

**Comment by yala** [comment]
@nicola 

Ahaha, we argued about this at 2am that night.
An `object` is like an `axe` or a `rock`
An `action`, by the weird pdll semantics is `furnace-make-glass`
I think we should scrap subgoals for now. Almost all of them are of the form:
'avalabable obj_name > 0'

A `thing` is a superset of 'actions', 'objects' etc.

That calling conventions lgtm

We should have an option for returning the setence as well for ease of logging, and a param for type of answer you'll give (per answer baselines), but i'll assume you return 1 feature vector for now

**Comment by yala** [comment]
@nicola 
Could you elaborate on the return convention

Could you give me an example of a `(Question, Answer)` pair?

It'd simplify my dev a little
Thanks!

**Comment by yala** [comment]
What difference does the template number make in your implementation?

Isn't it all BoW anyways? 
Can you elaborate an explain

Also, bump bump on the comment above

**Comment by nicola** [comment]
- The examples are in the issue, you need two pass two parameters the first being an int (question type) and the second being a string (the actual question)
- I would prefer not to skip the question template, your learner has no idea whether I am performing BoW or some other clever things

**Comment by yala** [comment]
@nicola I want an example of an answer, which is not in the issue, not in any concrete way

Do you plan on doing any clever things?

Also, can i just pass the template name instead of index, it'll be easier to keep track of. For name, see what i write in #3 
Otherwise, i'll just the mapping in cpp, and eww doing anything in cpp

**Comment by nicola** [comment]
- @yala I already do clever things when it comes between the difference of actions and objects
- Fine with that, will change my implementation according to #3

**Comment by yala** [comment]
@nicola 

Can pretty please see an example of answer? I realllllly need to concretely understand this.

**Comment by yala** [comment]
Also, what kind of clever things. Can you explain?

I'm worried we aren't on the same page here
