### ISSUE TITLE
Adding Questions to Policy

### ISSUE THREAD

**Issue by yala** [yala/learning_interactive_planning#3]
# Adding Questions to Policy

This is the body of work incorporating our question templates into **vec_CandidatePredicates**
## We want to support:
1. Question Baselines (See #2)
   - [x] Rule 0. `question_type=action`
   - [x] Rule 1. `question_type=object`
   - [ ] Rule 2. `question_type=subgoal`
   - [ ] Rule 3. `question_type=subgoal_pair`
2. Interpretability
   - [x] Way to distinguish PddlPredicate object as a question, rather than a regular subgoal
   - [x] Way to output human interpretable version of question ie. "Tell me about pickaxes" 
     (for qualitative analysis)
## Predicate Format

`PREDICATE_ID|0|question QUESTION_TYPE QUESTION_ARGUMENT`
## Return Convention

PddlPredicate

**Comment by yala** [comment]
@sebboyer @nicola 

And let's keep track of this here

**Comment by sebboyer** [comment]
Here the format I propose for the question related predicates (as written in the .dictionary files) 
<prediate id>|1| question <question type> <question argument>
E.g,
336|1|question object brick

**Comment by sebboyer** [comment]
Here the format I propose for the question related predicates (as written in the .dictionary file)
PREDICATE_ID|1|question QUESTION_TYPE QUESTION_ARGUMENT
E.g,
336|1|question object brick

**Comment by sebboyer** [comment]
I will create 2 additionnal .dictionnary files (in addition to valid_predicates.dictionnary)
valid_questions_objects.dictionary (containing object related questions)
valid_questions_actions.dictionary (containing action related questions)

**Comment by yala** [comment]
Lgtm!

**Comment by yala** [comment]
@sebboyer 
You wrote
`PREDICATE_ID|1|question QUESTION_TYPE QUESTION_ARGUMENT`

Could we change that to 
`PREDICATE_ID|0|question QUESTION_TYPE QUESTION_ARGUMENT`

The 0 marks it as predicate instead of a function, which it think better suits our needs

**Comment by nicola** [comment]
Give us news if any seb

**Comment by nicola** [comment]
I don't know who keeps on editing this issue, but DO REFER to THIS https://github.com/flare-ai/learning_from_questions/issues/2.

The rule enumerations in this issue are wrong

**Comment by yala** [comment]
I reordered the enum

**Comment by nicola** [comment]
@sebboyer make sure that your question arguments reflect the list here: https://github.com/flare-ai/learning_from_questions/blob/master/code/ir/vocab.py

So if an action `do-this`, you have to do:

`PREDICATE_ID|1|question 0 do-this`

**Comment by sebboyer** [comment]
@nicola what do you mean by P in the vocab.py file ? I have included a valid_questions_predicates.dictionary containing the values in the P set of vocab.py.

**Comment by sebboyer** [comment]
@yala I have changed the default of PREDICATE_VALUE from 1 to 0 as you suggested.

**Comment by nicola** [comment]
@sebboyer have a look at that file, that file has A, P and O

**Comment by sebboyer** [comment]
Yes I know I saw it. I am not sure what P stands for though.

**Comment by yala** [comment]
@sebboyer, thank you!

**Comment by nicola** [comment]
@sebboyer P is predicate

**Comment by nicola** [comment]
I marked the last point as done since the IR can do that
