### ISSUE TITLE
Predicates incorrectly numbed

### ISSUE THREAD

**Issue by yala** [yala/learning_interactive_planning#48]
Looking at the object question pred file, the numbers are wrong.

**Comment by nicola** [comment]
give me more detail on this, I think I know what you are talking about

**Comment by yala** [comment]
look at data/valid_predicates_questionsObject.dictionary

The numbering isn't sequential

**Comment by sebboyer** [comment]
I am not sure what you are saying. I have just look at the valid_prediates and it looks fine for me.

**Comment by yala** [comment]
Look at: 
https://github.com/flare-ai/learning_from_questions/blob/master/data/valid_predicates_questionsObject.dictionary 

In line 335, it jumps

`335|6|thing-available clayblock`
`405|0|question 1 shears`

**Comment by nicola** [comment]
why is that an issue?
they are just ids

**Comment by yala** [comment]
we may use the ids for indexing

Does not feel safe

We haven't tested on that dict file at all, but i think if we do, we will segfault

**Comment by nicola** [comment]
I am not sure I follow. Let's debug the segfault

**Comment by yala** [comment]
It's definitely a risk and a trivial fix.

I'll get to it later

**Comment by sebboyer** [comment]
I see  ... Wrong file. I can change the file name but we should use
valid_questions_objects.dictionary
