### ISSUE TITLE
Running the Project

### ISSUE THREAD

**Issue by yala** [yala/learning_interactive_planning#5]
# Running the Project
## Completed Tasks
- [x] Set up Docker and start scripts 
- [x] Getting sufficiently powerful machine
## Remaining Tasks
- [x] Getting enough space on machine
- [x] Successfully reproducing Branavan results

**Comment by yala** [comment]
@nicola @sebboyer, Let's discuss "Run shit" issues here

@nicola, Have you contact the old PhD student yet?

**Comment by nicola** [comment]
Just contacted the student, will let you know soon

**Comment by nicola** [comment]
We now have space

**Comment by nicola** [comment]
Can't get Branavan's results, I can only get them for small number of iterations.
Maybe docker dies? What can be our plan to get that working?

**Comment by yala** [comment]
@sebboyer @nicola 

No idea. Let's email Branavan about it

@nicola, do you want to write the email?
I think it'd make sense since you know the issue best.

**Comment by nicola** [comment]
I will hold and try to make it run, but in your email you can point out this:

> Nicola run the program but it only runs for a few iterations, otherwise it stops after 50 mins

**Comment by nicola** [comment]
See #13
